# This module defines the following CMake variables:
##   _FOUND
#  PCRTREE2_INCLUDE_DIRS
#  PCRTREE2_LIBRARIES
#

FIND_PATH(PCRTREE2_INCLUDE_DIRS
    NAMES pcrtree2/calc_spatial.h
    PATHS ${_PCRTREE2_ROOT_INCLUDE}
)

FIND_LIBRARY(PCRTREE2_MODELENGINE_LIBRARY
    NAMES pcraster_model_engine
    PATHS ${_PCRTREE2_ROOT_LIB}
)

FIND_LIBRARY(PCRTREE2_PYTHON_LIBRARY
    NAMES _pcraster.so
    PATHS ${PCRTREE2_INCLUDE_DIRS}/../python/pcraster # hack, but works fttb
)

SET(PCRTREE2_LIBRARIES
    ${PCRTREE2_MODELENGINE_LIBRARY}
    ${PCRTREE2_PYTHON_LIBRARY}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PCRTREE2
    REQUIRED_VARS
        PCRTREE2_LIBRARIES
        PCRTREE2_INCLUDE_DIRS
)
