option(M4S_BUILD_TEST FALSE)


set(DEVBASE_BOOST_REQUIRED TRUE)
list(APPEND DEVBASE_REQUIRED_BOOST_COMPONENTS
    python system)

set(DEVBASE_PYTHON_LIBS_REQUIRED TRUE)
set(DEVBASE_REQUIRED_PYTHON_VERSION 2.7)


if(M4S_BUILD_TEST)
    list(APPEND DEVBASE_REQUIRED_BOOST_COMPONENTS
        system unit_test_framework)
endif()


set(DEVBASE_FERN_REQUIRED TRUE)
set(M4S_PCRTREE2_REQUIRED TRUE)
